### ISSUE TITLE
Toolbar css problem

### ISSUE THREAD

**Issue by wonjunkang** [phuoc-ng/react-pdf-viewer#83] opened 2020-03-18 21:53 UTC
I tested the demo on create-react-app set up but the toolbar is broken like this.

![Screen Shot 2020-03-18 at 5 51 27 PM](https://user-images.githubusercontent.com/58698642/77011046-61091f80-6941-11ea-9fac-becb9e3efa9a.png)

**Comment by phuoc-ng** [comment] 2020-03-19 17:10
Thanks for reporting the bug. It will be fixed soon, as I'll add an example to work with `create-react-app`.

**Comment by phuoc-ng** [comment] 2020-03-29 02:37
@wonjunkang 
Here is the clean [demo](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/demo/create-react-app) using create-react-app.

Without the default setup of `create-react-app`, here is how the viewer looks like

<img width="1253" alt="Screen Shot 2020-03-29 at 09 31 17" src="https://user-images.githubusercontent.com/57786711/77838725-a4b12400-71a0-11ea-9a29-a1c63ec14052.png">

I guess the viewer's styles are effected by another CSS.
Can you give me the steps to reproduce or do you have a repo, so I can take a look?

**Comment by phuoc-ng** [comment] 2020-04-10 08:56
Can't produce.

**Closed by phuoc-ng** 2020-04-10 08:56 UTC

**Comment by wonjunkang** [comment] 2020-04-13 16:16
Thanks it works now!
